repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
