name: Update secrets

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  update_secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - Crocmagnon/charasheet
          - Crocmagnon/blog
        secret_name:
          - TEST_SECRET
#          - PR_APP_ID
#          - PR_APP_PRIVATE_KEY
    steps:
      - name: Update ${{ matrix.secret_name }} on ${{ matrix.repo }}
        uses: gliech/create-github-secret-action@v1.4.10
        with:
          location: ${{ matrix.repo }}
          name: ${{ matrix.secret_name }}
          value: ${{ secrets[matrix.secret_value] }}
          pa_token: ${{ secrets.UPDATE_SECRETS_TOKEN }}

