name: Update secrets

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  update_secrets:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.UPDATE_SECRETS_TOKEN }}
    strategy:
      matrix:
        repo:
          - Crocmagnon/charasheet
          - Crocmagnon/blog
          - Crocmagnon/hass_grdf_api
        secret_name:
          - PR_APP_ID
          - PR_APP_PRIVATE_KEY
          - DEPLOY_HOST
          - DEPLOY_KEY
          - DEPLOY_PORT
          - DEPLOY_USERNAME
          - DOCKERHUB_TOKEN
          - DOCKERHUB_USERNAME
    steps:
      - name: Update ${{ matrix.secret_name }} on ${{ matrix.repo }}
        run: |
          gh secret set ${{ matrix.secret_name }} -a actions -R ${{ matrix.repo }} < ${{ secrets[matrix.secret_value] }}  

