name: Update secrets

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  get_token:
    name: Get token
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate-token.outputs.token }}
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_APP_ID }}
          private_key: ${{ secrets.PR_APP_PRIVATE_KEY }}
  update_secrets:
    needs: get-token
    strategy:
      matrix:
        repo:
          - Crocmagnon/charasheet
          - Crocmagnon/blog
        include:
          - secret_name: TEST_SECRET
            secret_value: ${{ secrets.TEST_SECRET }}
#          - secret_name: PR_APP_ID
#            secret_value: ${{ secrets.PR_APP_ID }}
#          - secret_name: PR_APP_PRIVATE_KEY
#            secret_value: ${{ secrets.PR_APP_PRIVATE_KEY }}
    steps:
      - name: Update secret for ${{ matrix.repo }}
        uses: gliech/create-github-secret-action@v1.4.10
        with:
          location: ${{ matrix.repo }}
          name: ${{ matrix.secret_name }}
          value: ${{ matrix.secret_value }}
          pa_token: ${{ needs.get_token.outputs.token }}

