name: Update secrets

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ]
    paths: [ ".github/workflows/update-secrets.yaml" ]

permissions:
  contents: read

jobs:
  update_secrets:
    name: Update ${{ matrix.secret_name }} on ${{ matrix.repo }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.UPDATE_SECRETS_TOKEN }}
    strategy:
      matrix:
        repo:
          - Crocmagnon/charasheet
          - Crocmagnon/charasheet-go
          - Crocmagnon/blog
          - Crocmagnon/hass_grdf_api
          - Crocmagnon/checkout
        secret_name:
          - PR_APP_ID
          - PR_APP_PRIVATE_KEY
          - DEPLOY_HOST
          - DEPLOY_KEY
          - DEPLOY_PORT
          - DEPLOY_USERNAME
          - DOCKERHUB_TOKEN
          - DOCKERHUB_USERNAME
    steps:
      - name: Update secret
        run: |
          gh secret set ${{ matrix.secret_name }} -a actions -R ${{ matrix.repo }} -b "${{ secrets[matrix.secret_name] }}"
  delete_secrets:
    name: Delete ${{ matrix.secret_name }} on ${{ matrix.repo }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.UPDATE_SECRETS_TOKEN }}
    strategy:
      matrix:
        repo:
          - Crocmagnon/charasheet
          - Crocmagnon/blog
          - Crocmagnon/hass_grdf_api
          - Crocmagnon/checkout
        secret_name:
          - DUMMY_SECRET_NAME
    steps:
      - name: Delete secret
        run: |
          gh secret delete ${{ matrix.secret_name }} -a actions -R ${{ matrix.repo }} || true
